### ISSUE TITLE
Kubernetes 1.7 chart failures

### ISSUE THREAD

**Issue by foxish** [helm/charts#1294]
Reported failures from https://k8s-testgrid.appspot.com/kubernetes-apps

**Cockroachdb**:
W0613 14:19:20.823] Error: release wzq failed: StatefulSet.apps "wzq-cockroachdb" is invalid: spec.template.annotations.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey: Required value: can not be empty

**Spinnaker**: 
W0613 14:19:49.774] Error: found in requirements.yaml, but missing in charts/ directory: redis, minio

**Jenkins**:
W0613 14:19:51.019] Error: error validating "": error validating data: unexpected type: types.UnixUserID

cc @kubernetes/charts-maintainers @viglesiasce

**Comment by foxish** [comment]
- Opened https://github.com/kubernetes/charts/issues/1306 for cockroachdb
- Spinnaker is a test issue (needs install deps)
- Jenkins issue is being debated in https://github.com/kubernetes/kubernetes/issues/47448

**Comment by foxish** [comment]
Jenkins issue is now resolved because upstream k8s reverted the backward incompatible API change. The test is now passing. Cockroachdb will pass after we merge https://github.com/kubernetes/charts/issues/1306 on the day 1.7 releases.

**Comment by wclr** [comment]
Wound it be useful if one could change an arbitrary needed field in the resources definitions (that can not be changed via values abstraction), not by cloning/copy/pasting entire chart code and modifying the template?

I think helm charts has a kind of flaw abstraction model, that doesn't allow to reuse them in more flexible way.

**Comment by paulwalker** [comment]
I'd like to add that concourse.ci is also victim to this.

What exactly is the yaml workaround btw?

**Comment by paralin** [comment]
What's the fix for this?

**Comment by cmcconnell1** [comment]
Hello this issue persists confirmed installing according to README/doc.


```
helm install stable/concourse --namespace concourse
Error: release funky-cricket failed: StatefulSet.apps "funky-cricket-worker" is invalid: spec.template.annotations.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey: Required value: can not be empty

helm status funky-cricket | head -3
LAST DEPLOYED: Fri Oct 13 14:51:52 2017
NAMESPACE: concourse
STATUS: FAILED
```

Note that when deploying from source repo after checking for and installing any missing dependencies:
```
helm dep list
helm dep update 
helm dep build
```
. . . then helm install seems to get past the error and the deployment appears to be successful according to helm, but note that the postgresql and worker pods remain in pending state:

```
helm install stable/concourse -f $GIT_HOME/charts/stable/concourse/values.yaml --namespace concourse

helm status concourse | head -3
LAST DEPLOYED: Fri Oct 13 15:07:52 2017
NAMESPACE: concourse
STATUS: DEPLOYED

kubectl get all --namespace concourse
NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/concourse-postgresql   1         1         1            0           3m
deploy/concourse-web          1         1         1            0           3m

NAME                                 DESIRED   CURRENT   READY     AGE
rs/concourse-postgresql-4126483298   1         1         0         3m
rs/concourse-web-1449843452          1         1         0         3m

NAME                          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/concourse-postgresql   1         1         1            0           3m
deploy/concourse-web          1         1         1            0           3m

NAME                            DESIRED   CURRENT   AGE
statefulsets/concourse-worker   2         1         3m

NAME                                       READY     STATUS    RESTARTS   AGE
po/concourse-postgresql-4126483298-49w1v   0/1       Pending   0          3m
po/concourse-web-1449843452-1drm9          0/1       Running   1          3m
po/concourse-worker-0                      0/1       Pending   0          3m

```

Thanks

**Comment by jondlm** [comment]
I ran into a similar issue with `stable/concourse`. I had to run `helm repo update` to ensure that the newest chart version was getting installed. After that it worked for me.

**Comment by foxish** [comment]
This is likely out of date since 1.8 came out already. Individual issues should be filed for each of these against chart maintainers. Closing
