### ISSUE TITLE
incubator/vault get intermittent 403

### ISSUE THREAD

**Issue by continuum-yogesh-kunjir** [helm/charts#16307]
**Describe the bug**
I am getting an intermittent 403 from vault while performing any operation.

**Version of Helm and Kubernetes**: 
Helm is 2.13
Kubernetes is 1.11

**Which chart**:
incubator/vault v 0.18.6

**What happened**:
I was trying to do some operation on vault

**What you expected to happen**:
It should have return proper output instant of 403 every time

**How to reproduce it** (as minimally and precisely as possible):
Installed chart version 0.18.6 with auto seal unlock with aws and storage is S3

**Anything else we need to know**:
```

NAME                                  READY   STATUS    RESTARTS   AGE
vault-vault-8f467ff79-5xp5d   1/1     Running   0          19d
vault-vault-8f467ff79-7xnkf   1/1     Running   2          42d
vault-vault-8f467ff79-d7lkz   1/1     Running   0          19d

test@test:~$ vault kv put cubbyhole/hello foo=world
Error making API request.

URL: GET https://tooling.itsupport247.net/v1/sys/internal/ui/mounts/cubbyhole/hello
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "cubbyhole/hello/"

test@test:~$ vault kv put cubbyhole/hello foo=world
Key              Value
---              -----
created_time     2019-08-14T04:45:47.476581616Z
deletion_time    n/a
destroyed        false
version          2
test@test:~$ vault kv get cubbyhole/hello
Error making API request.

URL: GET https://tooling.itsupport247.net/v1/sys/internal/ui/mounts/cubbyhole/hello
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "cubbyhole/hello/"

test@test:~$ vault kv get cubbyhole/hello
====== Metadata ======
Key              Value
---              -----
created_time     2019-08-14T04:45:47.476581616Z
deletion_time    n/a
destroyed        false
version          2

=== Data ===
Key    Value
---    -----
foo    world

test@test:~$ vault kv delete cubbyhole/hello
Success! Data deleted (if it existed) at: cubbyhole/hello

test@test:~$ vault kv get cubbyhole/hello
Error making API request.

URL: GET https://tooling.itsupport247.net/v1/sys/internal/ui/mounts/cubbyhole/hello
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "cubbyhole/hello/"

test@test:~$ vault kv get cubbyhole/hello
====== Metadata ======
Key              Value
---              -----
created_time     2019-08-14T04:45:47.476581616Z
deletion_time    2019-08-14T04:46:02.73751689Z
destroyed        false
version          2
```

**Comment by continuum-yogesh-kunjir** [comment]
Hello all,

I have reduced pod from 3 to 1 and issue is resolved but the cause of unknown. we were getting error for api call via curl command.

if anyone have any idea please revert.

**Comment by nesl247** [comment]
We've had to do the same thing. I've never been able to get HA working.

**Comment by nesl247** [comment]
This is still an issue.

**Comment by zdevi** [comment]
@nesl247  S3 is not HA compatible, documentation sais to use DynamodDB backend to enable HA. I'm using Dynamodb on aws, and gcs bucket on GCP, both work with HA without problems.

**Comment by nesl247** [comment]
In my case I’m using MySQL as the storage backend and still getting the same issue.

**Comment by zdevi** [comment]
Never tried with mysql backend.

**Comment by jbialy** [comment]
I can also confirm that HA works properly with DynamoDB.
