### ISSUE TITLE
[stable/rabbitmq] Failed to get nodes from k8

### ISSUE THREAD

**Issue by james-millner** [helm/charts#17508]
**Describe the bug**
Failing to successfully deploy RabbitMQ to docker-for-desktop via the stable/rabbitmq helm chart. My steps to install the chart are as follows:

1. helm install
`
helm install stable/rabbitmq --name rabbitmq
`

2. Check kubernetes

```
Every 2.0s: kubectl get pods,secrets,svc,gateways,virtualservices                                James: Sat Sep 28 12:08:15 2019

NAME             READY   STATUS    RESTARTS   AGE
pod/rabbitmq-0   1/2     Running   2          46s

NAME                          TYPE                                  DATA   AGE
secret/default-token-9wb7r    kubernetes.io/service-account-token   3      82s
secret/istio.default          istio.io/key-and-cert                 3      81s
secret/istio.rabbitmq         istio.io/key-and-cert                 3      61s
secret/rabbitmq               Opaque                                2      62s
secret/rabbitmq-token-p5p68   kubernetes.io/service-account-token   3      62s

NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                 AGE
service/kubernetes          ClusterIP   10.96.0.1        <none>        443/TCP                                 77s
service/rabbitmq            ClusterIP   10.104.106.255   <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   62s
service/rabbitmq-headless   ClusterIP   None             <none>        4369/TCP,5672/TCP,25672/TCP,15672/TCP   62s
```

3. Inspect the stateful sets logs

```
2019-09-28 11:07:57.696 [info] <0.232.0> Memory high watermark set to 4797 MiB (5030302515 bytes) of 11993 MiB (12575756288 bytes) total
2019-09-28 11:07:57.700 [info] <0.234.0> Enabling free disk space monitoring
2019-09-28 11:07:57.700 [info] <0.234.0> Disk free limit set to 50MB
2019-09-28 11:07:57.704 [info] <0.237.0> Limiting to approx 65436 file handles (58890 sockets)
2019-09-28 11:07:57.704 [info] <0.238.0> FHC read buffering:  OFF
2019-09-28 11:07:57.704 [info] <0.238.0> FHC write buffering: ON
2019-09-28 11:07:57.705 [info] <0.224.0> Node database directory at /opt/bitnami/rabbitmq/var/lib/rabbitmq/mnesia/rabbit@10.1.3.119 is empty. Assuming we need to join an existing cluster or initialise from scratch...
2019-09-28 11:07:57.705 [info] <0.224.0> Configured peer discovery backend: rabbit_peer_discovery_k8s
2019-09-28 11:07:57.705 [info] <0.224.0> Will try to lock with peer discovery backend rabbit_peer_discovery_k8s
2019-09-28 11:07:57.705 [info] <0.224.0> Peer discovery backend does not support locking, falling back to randomized delay
2019-09-28 11:07:57.705 [info] <0.224.0> Peer discovery backend rabbit_peer_discovery_k8s does not support registration, skipping randomized startup delay.
2019-09-28 11:07:57.715 [info] <0.224.0> Failed to get nodes from k8s - {failed_connect,[{to_address,{"kubernetes.default.svc.cluster.local",443}},
                 {inet,[inet],closed}]}
2019-09-28 11:07:57.715 [error] <0.223.0> CRASH REPORT Process <0.223.0> with 0 neighbours exited with reason: no case clause matching {error,"{failed_connect,[{to_address,{\"kubernetes.default.svc.cluster.local\",443}},\n                 {inet,[inet],closed}]}"} in rabbit_mnesia:init_from_config/0 line 164 in application_master:init/4 line 138
2019-09-28 11:07:57.716 [info] <0.43.0> Application rabbit exited with reason: no case clause matching {error,"{failed_connect,[{to_address,{\"kubernetes.default.svc.cluster.local\",443}},\n                 {inet,[inet],closed}]}"} in rabbit_mnesia:init_from_config/0 line 164
2019-09-28 11:07:57.717 [error] <0.107.0> Failed to write log message to file /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@10.1.3.119.log: invalid argument
{"Kernel pid terminated",application_controller,"{application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,\"{failed_connect,[{to_address,{\\"kubernetes.default.svc.cluster.local\\",443}},\n                 {inet,[inet],closed}]}\"}},[{rabbit_mnesia,init_from_config,0,[{file,\"src/rabbit_mnesia.erl\"},{line,164}]},{rabbit_mnesia,init_with_lock,3,[{file,\"src/rabbit_mnesia.erl\"},{line,144}]},{rabbit_mnesia,init,0,[{file,\"src/rabbit_mnesia.erl\"},{line,111}]},{rabbit_boot_steps,'-run_step/2-lc$^1/1-1-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,49}]},{rabbit_boot_steps,run_step,2,[{file,\"src/rabbit_boot_steps.erl\"},{line,49}]},{rabbit_boot_steps,'-run_boot_steps/1-lc$^0/1-0-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,26}]},{rabbit_boot_steps,run_boot_steps,1,[{file,\"src/rabbit_boot_steps.erl\"},{line,26}]},{rabbit,start,2,[{file,\"src/rabbit.erl\"},{line,907}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,"{failed_connect,[{to_address,{\"kubernetes.defau

Crash dump is being written to: /opt/bitnami/rabbitmq/var/log/rabbitmq/erl_crash.dump...done
```

**Version of Helm and Kubernetes**:
Kubernetes docker-for-desktop: 1.14.6
Helm: Client(v2.14.3) & Server(v2.14.3)

**Which chart**:
stable/rabbitmq

**What happened**:
The stateful set continously crashes and never reaches a ready state, exposing 5672 && 15672

**What you expected to happen**:
A instance of RabbitMQ to be deployed into docker-for-desktop context.

**How to reproduce it** (as minimally and precisely as possible):

1. Purge RabbitMQ
```
helm del --purge rabbitmq
```

2. Install fresh

```
helm install stable/rabbitmq --name rabbitmq
```

**Anything else we need to know**:
Running a single node docker-for-desktop setup, but this also occurs on a GCP GKE 3 node cluster running kubernetes: 1.13.7-gke.19

Which leads me to believe its probably something I'm doing wrong, can anyone help with the above? 👍

**Comment by rafariossaa** [comment]
Hi @james-millner,
  Have you tried removing the pvc after the `helm del --purge` ?

**Comment by james-millner** [comment]
Hi @rafariossaa,

I don't see any PVC resources after `helm del --purge rabbitmq`

**Comment by denis111** [comment]
The same just happend after upgrading EKS cluster from 1.13 to 1.14. Running test rabbitmq without any PVC:

2019-10-07 06:22:11.395 [info] <0.235.0> Failed to get nodes from k8s - {failed_connect,[{to_address,{"kubernetes.default.svc.cluster.local",443}},
                 {inet,[inet],nxdomain}]}
2019-10-07 06:22:11.396 [error] <0.234.0> CRASH REPORT Process <0.234.0> with 0 neighbours exited with reason: no case clause matching {error,"{failed_connect,[{to_address,{\"kubernetes.default.svc.cluster.local\",443}},\n                 {inet,[inet],nxdomain}]}"} in rabbit_mnesia:init_from_config/0 line 167 in application_master:init/4 line 138
2019-10-07 06:22:11.396 [info] <0.43.0> Application rabbit exited with reason: no case clause matching {error,"{failed_connect,[{to_address,{\"kubernetes.default.svc.cluster.local\",443}},\n                 {inet,[inet],nxdomain}]}"} in rabbit_mnesia:init_from_config/0 line 167
{"Kernel pid terminated",application_controller,"{application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,\"{failed_connect,[{to_address,{\\"kubernetes.default.svc.cluster.local\\",443}},\n                 {inet,[inet],nxdomain}]}\"}},[{rabbit_mnesia,init_from_config,0,[{file,\"src/rabbit_mnesia.erl\"},{line,167}]},{rabbit_mnesia,init_with_lock,3,[{file,\"src/rabbit_mnesia.erl\"},{line,147}]},{rabbit_mnesia,init,0,[{file,\"src/rabbit_mnesia.erl\"},{line,114}]},{rabbit_boot_steps,'-run_step/2-lc$^1/1-1-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,55}]},{rabbit_boot_steps,run_step,2,[{file,\"src/rabbit_boot_steps.erl\"},{line,52}]},{rabbit_boot_steps,'-run_boot_steps/1-lc$^0/1-0-',1,[{file,\"src/rabbit_boot_steps.erl\"},{line,28}]},{rabbit_boot_steps,run_boot_steps,1,[{file,\"src/rabbit_boot_steps.erl\"},{line,26}]},{rabbit,start,2,[{file,\"src/rabbit.erl\"},{line,933}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{{case_clause,{error,"{failed_connect,[{to_address,{\"kubernetes.defau

**Comment by denis111** [comment]
Well, after 14 restarts it just worked :)

**Comment by james-millner** [comment]
@denis111 I've not been able to get it running at all :(

**Comment by barryib** [comment]
@james-millner is this PR helps you https://github.com/helm/charts/pull/17987 ?

It adds `automountServiceAccountToken: true` for service account.

**Comment by jwalton** [comment]
Happening to me, too.  My config is:

```yaml
  service:
    type: NodePort
  rabbitmq:
    username: guest
    password: guest
  persistence:
    enabled: false
  metrics:
    enabled: true
```

**Comment by barryib** [comment]
@jwalton Can you share your logs please.

**Comment by jwalton** [comment]
https://gist.github.com/jwalton/f6d1ee69f1766c1a13eb616e201e9c28

**Comment by jwalton** [comment]
I tried adding `automountServiceAccountToken: true` to the service account, but it doesn't seem to have helped.

This problem also seems to be intermittent - after 8 restarts RabbitMQ did eventually start correctly.  Restarting it again set it to crashing repeatedly again, though.

**Comment by barryib** [comment]
Are you tried to run your rabbitmq nodes in debug to get more info ?

Another option: Is your service and endpoints for kubernetes.default.svc.cluster.local are running correctly ? Can you resolve (DNS) it from your pods ?

**Comment by jwalton** [comment]
I haven't tried debug mode.  Is there an easy way to do such a thing?

kubernetes.default.svc.cluster.local does resolve:

```
bash-4.4# host kubernetes.default.svc.cluster.local
kubernetes.default.svc.cluster.local has address 10.100.0.1
```

I'm running this on an EKS cluster I created about a week ago.  It's a pretty standard Kubernetes deployment.

**Comment by barryib** [comment]
You have to play with https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml#L128 and https://www.rabbitmq.com/logging.html#log-levels

**Comment by jwalton** [comment]
It's coming up consistently for me now.  I did reboot my coredns pods, which may or may not have played a part.  :/

**Comment by fhaase2** [comment]
Still an issue

**Comment by aixeshunter** [comment]
Still an issue

**Comment by tschirmer** [comment]
still an issue

**Comment by tschirmer** [comment]
Was running calico, and didn't allow an outbound port 53 for DNS resolution, this was solved now.

```
---
# Source: custom-app/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-rabbitmq-inbound
  namespace: custom-app-namespace
  labels:
    app.kubernetes.io/component: rabbitmq
    app: custom-app
spec:
  podSelector:
    matchLabels:
      app: rabbitmq
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: custom-app-namespace
          podSelector:
            matchLabels:
              rabbitmq.client: "true"
      ports:
        - protocol: TCP
          port: 5672
    - from:
        - namespaceSelector:
            matchLabels:
              name: custom-app-namespace
          podSelector:
            matchLabels:
              app: rabbitmq
      ports:
        - protocol: TCP
          port: 15672
        - protocol: TCP
          port: 4369
        - protocol: TCP
          port: 5672
  egress:
    - ports:
        - protocol: UDP
          port: 53 # Allow dns resolution
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector:
            matchLabels:
              name: custom-app-namespace
          podSelector:
            matchLabels:
              app: rabbitmq
      ports:
        - protocol: TCP
          port: 15672
        - protocol: TCP
          port: 4369
        - protocol: TCP
          port: 5672
```

**Comment by tschirmer** [comment]
Could probably change this into a pull request; add in the helm tempting tags, and add in restriction to only that release.

**Comment by KarthikReddy12345** [comment]
I got the same issue but i didn't use HELM. I'm deploying the YAML template in Openshift.
-------------------------------------------------------------------------------------------------------------


Starting broker...2021-03-30 08:39:53.352 [info] <0.273.0>
--
  | node           : rabbit@rabbitmq-cluster-0.rabbitmq-cluster.rabbitmq.svc.cluster.local
  | home dir       : /var/lib/rabbitmq
  | config file(s) : /var/lib/rabbitmq/rabbitmq.conf
  | cookie hash    : rRQL4RxGmv6haVOQ4ocT3g==
  | log(s)         : <stdout>
  | database dir   : /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-cluster-0.rabbitmq-cluster.rabbitmq.svc.cluster.local
  | 2021-03-30 08:39:53.559 [debug] <0.284.0> Lager installed handler lager_backend_throttle into lager_event
  | 2021-03-30 08:39:54.357 [info] <0.273.0> Feature flags: list of feature flags found:
  | 2021-03-30 08:39:54.357 [info] <0.273.0> Feature flags:   [ ] drop_unroutable_metric
  | 2021-03-30 08:39:54.357 [info] <0.273.0> Feature flags:   [ ] empty_basic_get_metric
  | 2021-03-30 08:39:54.357 [info] <0.273.0> Feature flags:   [ ] implicit_default_bindings
  | 2021-03-30 08:39:54.357 [info] <0.273.0> Feature flags:   [ ] maintenance_mode_status
  | 2021-03-30 08:39:54.357 [info] <0.273.0> Feature flags:   [ ] quorum_queue
  | 2021-03-30 08:39:54.357 [info] <0.273.0> Feature flags:   [ ] user_limits
  | 2021-03-30 08:39:54.357 [info] <0.273.0> Feature flags:   [ ] virtual_host_metadata
  | 2021-03-30 08:39:54.357 [info] <0.273.0> Feature flags: feature flag states written to disk: yes
  | 2021-03-30 08:39:57.541 [info] <0.273.0> Running boot step pre_boot defined by app rabbit
  | 2021-03-30 08:39:57.541 [info] <0.273.0> Running boot step rabbit_core_metrics defined by app rabbit
  | 2021-03-30 08:39:57.541 [info] <0.273.0> Running boot step rabbit_alarm defined by app rabbit
  | 2021-03-30 08:39:57.546 [info] <0.356.0> Memory high watermark set to 3183 MiB (3338574233 bytes) of 7959 MiB (8346435584 bytes) total
  | 2021-03-30 08:39:57.550 [info] <0.358.0> Enabling free disk space monitoring
  | 2021-03-30 08:39:57.550 [info] <0.358.0> Disk free limit set to 50MB
  | 2021-03-30 08:39:57.554 [info] <0.273.0> Running boot step code_server_cache defined by app rabbit
  | 2021-03-30 08:39:57.554 [info] <0.273.0> Running boot step file_handle_cache defined by app rabbit
  | 2021-03-30 08:39:57.554 [info] <0.361.0> Limiting to approx 1048479 file handles (943629 sockets)
  | 2021-03-30 08:39:57.555 [info] <0.362.0> FHC read buffering:  OFF
  | 2021-03-30 08:39:57.555 [info] <0.362.0> FHC write buffering: ON
  | 2021-03-30 08:39:57.555 [info] <0.273.0> Running boot step worker_pool defined by app rabbit
  | 2021-03-30 08:39:57.555 [info] <0.347.0> Will use 2 processes for default worker pool
  | 2021-03-30 08:39:57.555 [info] <0.347.0> Starting worker pool 'worker_pool' with 2 processes in it
  | 2021-03-30 08:39:57.556 [info] <0.273.0> Running boot step database defined by app rabbit
  | 2021-03-30 08:39:57.556 [info] <0.273.0> Node database directory at /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-cluster-0.rabbitmq-cluster.rabbitmq.svc.cluster.local is empty. Assuming we need to join an existing cluster or initialise from scratch...
  | 2021-03-30 08:39:57.556 [info] <0.273.0> Configured peer discovery backend: rabbit_peer_discovery_k8s
  | 2021-03-30 08:39:57.557 [info] <0.273.0> Will try to lock with peer discovery backend rabbit_peer_discovery_k8s
  | 2021-03-30 08:39:57.557 [info] <0.273.0> Peer discovery backend does not support locking, falling back to randomized delay
  | 2021-03-30 08:39:57.557 [info] <0.273.0> Peer discovery backend rabbit_peer_discovery_k8s supports registration.
  | 2021-03-30 08:39:57.557 [info] <0.273.0> Will wait for 1403 milliseconds before proceeding with registration...
  | 2021-03-30 08:40:06.964 [error] <0.273.0> Failed to fetch a list of nodes from Kubernetes API: {failed_connect,[{to_address,{"kubernetes.default.svc.cluster.local",443}},
  | {inet,[inet],nxdomain}]}
  | 2021-03-30 08:40:14.972 [error] <0.273.0> Peer discovery returned an error: "{failed_connect,[{to_address,{\"kubernetes.default.svc.cluster.local\",443}},\n                 {inet,[inet],nxdomain}]}". Will retry after a delay of 500 ms, 9 retries left...
  | 2021-03-30 08:40:23.488 [error] <0.273.0> Failed to fetch a list of nodes from Kubernetes API: {failed_connect,[{to_address,{"kubernetes.default.svc.cluster.local",443}},
  | {inet,[inet],nxdomain}]}
  | 2021-03-30 08:40:31.498 [error] <0.273.0> Peer discovery returned an error: "{failed_connect,[{to_address,{\"kubernetes.default.svc.cluster.local\",443}},\n                 {inet,[inet],nxdomain}]}". Will retry after a delay of 500 ms, 8 retries left...
  | 2021-03-30 08:40:40.010 [error] <0.273.0> Failed to fetch a list of nodes from Kubernetes API: {failed_connect,[{to_address,{"kubernetes.default.svc.cluster.local",443}},
  | {inet,[inet],nxdomain}]}
  | 2021-03-30 08:40:41.051 [info] <0.60.0> SIGTERM received - shutting down

**Comment by orenlevi** [comment]
still getting this when trying to deploying using argocd app, when installing the same using helm it works.

**Comment by harshakondreddy** [comment]
I had the same issue, in my case it worked after restarting the network pod in kube-system namespaces.
 I am using weave-net and kube-proxy.

**Comment by yimiaoxiehou** [comment]
hello， I  resolve this problem by add hostAlias in statefulset 。 
```
          hostAliases:
          - ip: 10.43.0.1
            hostnames:
            - kubernetes.default.svc.cluster.local
```
everyone can try it.
@harshakondreddy  @orenlevi

**Comment by yimiaoxiehou** [comment]
i think this problem maybe is the rabbitmq cannot resolv dns.
