### ISSUE TITLE
stable/kubernetes-dashboard: User "system:serviceaccount:default:default" cannot create secrets in the namespace "kube-system"

### ISSUE THREAD

**Issue by dkirrane** [helm/charts#3104]
**Is this a request for help?**: yes

---

**BUG REPORT**

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

**Which chart**:
helm install stable/kubernetes-dashboard --version 0.4.2 --name kube-dash

**What happened**:
Kubernetes dashboard container is STATUS:Running
But the logs show this error:
```
2017/12/19 17:55:15 Starting overwatch
panic: secrets is forbidden: User "system:serviceaccount:default:default" cannot create secrets in the namespace "kube-system"
goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).init(0xc420218d80)
        /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:132 +0x2d3
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.NewRSAKeyHolder(0x2007400, 0xc4202e5540, 0xc4202e5540, 0x1663946)
        /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:171 +0x83
main.initAuthManager(0x20065c0, 0xc42022a780, 0x384, 0x1, 0x1)
        /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:132 +0x12f
main.main()
        /home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:84 +0x26c
```

**What you expected to happen**:
I expected the Helm chart to include all the Roles required. What role am I missing?

I edited the `kube-dash-kubernetes-dashboard` service to make it NodePort and tried to access it from Browser but got ERR_CONNECTION_TIMED_OUT 

**How to reproduce it** (as minimally and precisely as possible):
```
helm init
helm repo update
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm install stable/kubernetes-dashboard --version 0.4.2 --name kube-dash
```

**Anything else we need to know**:
```
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mattfarina** [comment]
cc @kfox1111

**Comment by xeor** [comment]
You will get this message if you don't set `rbac.create`, and you are using rbac.

**Comment by seeekr** [comment]
In version 0.5.2 of the chart this error is solved by specifying `--set rbac.create=true`, but in 0.6.0 the above error is occurring. Bug? Or is there more configuration settings that need to be applied when installing now?

**Comment by stuffandthings** [comment]
also getting the same issue, I've got `rbac.create` as true in my `values.yaml` file

**Comment by luisyonaldo** [comment]
err is not related to the chart.. https://github.com/kubernetes/dashboard/issues/2655

**Comment by caulagi** [comment]
This has worked for me - `helm install stable/kubernetes-dashboard --set rbac.create=false`

**Comment by quorak** [comment]
The issue exists quite a while. Would be good for new helm users to address this in the Readme. e.g.: 
`helm install stable/kubernetes-dashboard --namespace kube-system`

**Comment by simplytunde** [comment]
I ran into the same issue and what @quorak suggested go me past the issue

**Comment by monotek** [comment]
So does this mean i have to use kube-system as namespace?
Other namespaces are not working?

**Comment by tamama** [comment]
Hi,

After trying:
helm install stable/kubernetes-dashboard --namespace kube-system

I got this:

![image](https://user-images.githubusercontent.com/17287685/39751908-5c3c6da8-52ec-11e8-8121-0570f0e7f080.png)

Any idea?

**Comment by tamama** [comment]
And any way to work with other namespaces, eg. default?

**Comment by ArcticSnowman** [comment]
Seems dashboard is expected to be in kube-system and does not easily run in other namespaces.

**Comment by monotek** [comment]
Imho this is fixed. I run my dashboards in different namespaces...

**Comment by kfox1111** [comment]
The dashboard is particularly tricky to deal with because of the way authentication works in kube-dashboard and k8s today.
I'd recommend looking at: https://itnext.io/protect-kubernetes-dashboard-with-openid-connect-104b9e75e39c for a good way to use the chart with authentication.

We might be able to roll that other chart into the kube-dashboard so that they are deployed together. Any thoughts on that?

**Comment by kfox1111** [comment]
oh. this is about running it in a different namespace rather then the authentication bits. sorry. I misread. 

Yeah, it isn't a problem with the chart but kube-dashboard itself needs to fix that issue.

**Comment by hans-d** [comment]
imho would be good to leave this open as various people encounter the issue (even if it's not directly caused by the chart)

**Comment by EmperorArthur** [comment]
This is still an issue.

Attempted to follow the [instructions](https://www.digitalocean.com/community/tutorials/how-to-install-software-on-kubernetes-clusters-with-the-helm-package-manager) from DigitalOcean, and ran into this issue today.

Please re-open.

**Comment by KIVagant** [comment]
Of course `rbac.create=true` must be set during the installation. But if you want to have a read only Kubernetes Dashboard, you may probably want to change its role to something like [described here](http://blog.cowger.us/2018/07/03/a-read-only-kubernetes-dashboard.html).
In this case you will get the error.
To fix the problem, copy this part from the Helm chart to your new role:
```
  # Allow Dashboard to get, update and delete Dashboard exclusive secrets.
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - kubernetes-dashboard-key-holder
      - {{ template "kubernetes-dashboard.fullname" . }}
    verbs:
      - get
      - update
      - delete

  # Allow Dashboard to get and update 'kubernetes-dashboard-settings' config map.
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - kubernetes-dashboard-settings
    verbs:
      - get
      - update
```

The change is also available in the PR:
https://github.com/helm/charts/pull/12496/files

**Comment by denniswebb** [comment]
Adding note for other Googlers. If you are on chart 1.4.0, I had to run `kubectl -n kube-system create secret generic kubernetes-dashboard-key-holder` so the secret existed for the readonly account

**Comment by eightlimbed** [comment]
I got here from googling an error message deploying the dashboard in a namespace other than `kubernetes-dashboard`. I am not using helm. My issue was that I had `--namespace=kubernetes-dashboard` in the container args section of the Deployment. I missed it because I did a find and replace on `namespace: kubernetes-dashboard`, doh! Changing the flad to the namespace I wanted solved the problem.
